name: bicolit
description: A Flutter project for Bicol IT Org.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.1+2

dependencies:
  flutter:
    sdk: flutter
    
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.8
  firebase_storage: ^3.0.6
  localstorage: ^2.0.0
  email_validator: ^1.0.0
  flutter_datetime_picker:
    git:
      url: https://github.com/Zazo032/flutter_datetime_picker.git
  date_format: ^1.0.8
  image_picker: 0.4.0
  uuid: ^2.0.2
  progress_dialog: ^1.2.0
  pull_to_refresh: ^1.5.7
  rflutter_alert: ^1.0.3
  lodash_dart: ^0.0.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter:
  http: ^0.12.0+1
  rxdart: ^0.21.0
  flutter_masked_text: ^0.8.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  random_pk:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - locale/i18n_en.json
    - locale/i18n_hi.json
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          style: normal
        - asset: assets/fonts/Quicksand_Bold.otf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway-Medium.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
